spring:
    main:
        allow-circular-references: true
    application:
        name: appointment50
    datasource:
        url: jdbc:postgresql://localhost:15001/appointment50
        username: tk-apap-50
        password: tk-apap-50
    jpa:
        properties:
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation: true
                dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
server:
    port: 8081
appointment50:
    app:
        jwtSecret: "hPjbJwZKskRmCnzroyAZfglqSKexYmxKeYPvSvJ"
        jwtExpirationMs: 86400000